// Generated by apps/parser/csv.ts. Do not edit by hand.
import { decode } from '@msgpack/msgpack';

export const ActivityBarFormatVersion = 1;
export const ActivityBarSchemaHash = "729a65817bba137f865f5cedfdcd01fd2bacec8ee94430cd78e015a2a5a64b21";
/** Compact on-wire layout. Id exists only long enough to build ActivityBarTable. */
export type ActivityBarWireRow = readonly [
    Id: number,
    Skin: readonly number[],
    Title: number,
    Desc: number,
    ScoreGets: readonly number[],
    ActivityReturnRate: number,
    ProgressRate: number,
    BarID: readonly number[],
];
/** @deprecated Use ActivityBarWireRow for binary-level code or ActivityBar for business code. */
export type ActivityBarRow = ActivityBarWireRow;
export interface ActivityBar {
    readonly Skin: readonly number[],
    readonly Title: number,
    readonly Desc: number,
    readonly ScoreGets: readonly number[],
    readonly ActivityReturnRate: number,
    readonly ProgressRate: number,
    readonly BarID: readonly number[],
}
export const ActivityBarField = {
    "Id": 0,
    "Skin": 1,
    "Title": 2,
    "Desc": 3,
    "ScoreGets": 4,
    "ActivityReturnRate": 5,
    "ProgressRate": 6,
    "BarID": 7,
} as const;

export class ActivityBarTable {
    private readonly byId = new Map<number, ActivityBar>();

    constructor(rows: readonly ActivityBarWireRow[]) {
        for (const row of rows) {
            const id = row[0];
            if (typeof id !== 'number' || this.byId.has(id)) throw new Error('invalid ActivityBar Id');
            this.byId.set(id, {
                Skin: row[1],
                Title: row[2],
                Desc: row[3],
                ScoreGets: row[4],
                ActivityReturnRate: row[5],
                ProgressRate: row[6],
                BarID: row[7],
            });
        }
    }

    find(id: number): ActivityBar | undefined {
        return this.byId.get(id);
    }

    get(id: number): ActivityBar {
        const config = this.byId.get(id);
        if (!config) throw new Error('ActivityBar not found: ' + id);
        return config;
    }

    entries(): IterableIterator<[number, ActivityBar]> {
        return this.byId.entries();
    }
}
export function decodeActivityBar(bytes: Uint8Array): ActivityBarTable {
    const envelope = decode(bytes);
    if (!Array.isArray(envelope) || envelope.length !== 3) throw new Error('invalid ActivityBar config envelope');
    const [version, hash, rows] = envelope;
    if (version !== ActivityBarFormatVersion || hash !== ActivityBarSchemaHash) {
        throw new Error('ActivityBar config/client schema mismatch');
    }
    if (!Array.isArray(rows)) throw new Error('invalid ActivityBar config rows');
    return new ActivityBarTable(rows as ActivityBarWireRow[]);
}
