// Generated by apps/parser/csv.ts. Do not edit by hand.
import { decode } from '@msgpack/msgpack';
import * as z from 'zod';

export const ActivityBarFormatVersion = 1;
export const ActivityBarSchemaHash = "729a65817bba137f865f5cedfdcd01fd2bacec8ee94430cd78e015a2a5a64b21";
/** Compact on-wire layout. Id exists only long enough to build ActivityBarTable. */
export type ActivityBarWireRow = readonly [
    Id: number,
    Skin: readonly number[],
    Title: number,
    Desc: number,
    ScoreGets: readonly number[],
    ActivityReturnRate: number,
    ProgressRate: number,
    BarID: readonly number[],
];
/** @deprecated Use ActivityBarWireRow for binary-level code or ActivityBar for business code. */
export type ActivityBarRow = ActivityBarWireRow;
/** Object shape used by gameplay code; Id remains the ActivityBarTable key. */
export const ActivityBarSchema = z.object({
    Skin: z.array(z.number().int().min(-2147483648).max(2147483647)).readonly(),
    Title: z.number().int().min(-2147483648).max(2147483647),
    Desc: z.number().int().min(-2147483648).max(2147483647),
    ScoreGets: z.array(z.number().int().min(-2147483648).max(2147483647)).readonly(),
    ActivityReturnRate: z.number().int().min(-2147483648).max(2147483647),
    ProgressRate: z.number().int().min(-2147483648).max(2147483647),
    BarID: z.array(z.number().int().min(-2147483648).max(2147483647)).readonly(),
}).readonly();
export type ActivityBar = z.infer<typeof ActivityBarSchema>;
const ActivityBarIdSchema = z.number().int().min(-2147483648).max(2147483647);
export interface ActivityBarDecodeOptions {
    /** Validate decoded rows once. Enable for remote config, QA, or diagnosis builds. */
    readonly validate?: boolean;
}
export const ActivityBarField = {
    "Id": 0,
    "Skin": 1,
    "Title": 2,
    "Desc": 3,
    "ScoreGets": 4,
    "ActivityReturnRate": 5,
    "ProgressRate": 6,
    "BarID": 7,
} as const;

export class ActivityBarTable {
    private readonly byId = new Map<number, ActivityBar>();

    constructor(rows: readonly ActivityBarWireRow[], options: ActivityBarDecodeOptions = {}) {
        for (const row of rows) {
            const id = row[0];
            if (typeof id !== 'number' || this.byId.has(id)) throw new Error('invalid ActivityBar Id');
            if (options.validate) {
                const idResult = ActivityBarIdSchema.safeParse(id);
                if (!idResult.success) throw new Error('invalid ActivityBar Id ' + id + ': ' + idResult.error.message);
            }

            const config: ActivityBar = {
                Skin: row[1],
                Title: row[2],
                Desc: row[3],
                ScoreGets: row[4],
                ActivityReturnRate: row[5],
                ProgressRate: row[6],
                BarID: row[7],
            };
            if (options.validate) {
                const configResult = ActivityBarSchema.safeParse(config);
                if (!configResult.success) {
                    throw new Error('invalid ActivityBar Id ' + id + ': ' + configResult.error.message);
                }
                this.byId.set(id, configResult.data);
                continue;
            }
            this.byId.set(id, config);
        }
    }

    find(id: number): ActivityBar | undefined {
        return this.byId.get(id);
    }

    get(id: number): ActivityBar {
        const config = this.byId.get(id);
        if (!config) throw new Error('ActivityBar not found: ' + id);
        return config;
    }

    entries(): IterableIterator<[number, ActivityBar]> {
        return this.byId.entries();
    }
}
export function decodeActivityBar(bytes: Uint8Array, options: ActivityBarDecodeOptions = {}): ActivityBarTable {
    const envelope = decode(bytes);
    if (!Array.isArray(envelope) || envelope.length !== 3) throw new Error('invalid ActivityBar config envelope');
    const [version, hash, rows] = envelope;
    if (version !== ActivityBarFormatVersion || hash !== ActivityBarSchemaHash) {
        throw new Error('ActivityBar config/client schema mismatch');
    }
    if (!Array.isArray(rows)) throw new Error('invalid ActivityBar config rows');
    return new ActivityBarTable(rows as ActivityBarWireRow[], options);
}
